# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispanserization',
            fields=[
                ('dispanserization_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispanserization_group', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'dispanserization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor_specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('passport', models.CharField(max_length=20)),
                ('dispanserization_activity', models.IntegerField()),
                ('joining_staff', models.BooleanField()),
                ('telephone_num', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('icd10_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'icd10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Icd10Class',
            fields=[
                ('class_field', models.CharField(db_column='class', max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'icd10_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Icd10Subclass',
            fields=[
                ('subclass', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subclass_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'icd10_subclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True)),
                ('date_birth', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('medical_policynum', models.CharField(max_length=30)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(max_length=20)),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsAdmission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_time', models.DateTimeField()),
                ('symtoms', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients_admission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('free', models.BooleanField()),
            ],
            options={
                'db_table': 'patients_appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationOfSickPeople',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'registration_of_sick_people',
                'managed': False,
            },
        ),
    ]
