# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dispanserization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctorspecialization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='icd10',
            options={},
        ),
        migrations.AlterModelOptions(
            name='icd10class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='icd10subclass',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientsadmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientsappointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationofsickpeople',
            options={},
        ),
    ]
